# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  #
  # pain rectangles

  # ...cough...

  #
  # mono splits

  - board: nice_nano_v2
    shield: ffkb_v3

  - board: nice_nano_v2
    shield: ffkb_lite_v1

  - board: sparkfun_pro_micro_rp2040
    shield: reviung41

  - board: vik_cirque_i2c
    shield: pinkies_out_v3@3.0.0
#
  #
  # splits

  - board: nice_nano_v2
    shield: kyria_left
  - board: nice_nano_v2
    shield: kyria_right

  # - board: seeeduino_xiao_ble
  #   shield: bykeeb_left
  # - board: seeeduino_xiao_ble
  #   shield: bykeeb_right

  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right

  - board: nice_nano_v2
    shield: kyria_rev3
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: kyria_rev3

  - board: nice_nano_v2
    shield: anywhy_flake_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: anywhy_flake_right

  #
  # accessories

  # - board: seeeduino_xiao_ble
    # shield: adept

  #
  # resets

  - board: nice_nano_v2
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
