# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  #
  # pain rectangles

  # ...cough...

  #
  # mono splits

  - shield: ffkb_v2
    board: nice_nano_v2

  - shield: ffkb_v3
    board: nice_nano_v2

  # - shield: ffkb_lite_v1
  #   board: nice_nano_v2

  - shield: reviung41
    board: sparkfun_pro_micro_rp2040

  - shield: vik_cirque_i2c
    board: pinkies_out_v3@3.0.0
#
  #
  # splits

  - shield: kyria_rev3_left
    board: nice_nano_v2
  - shield: kyria_rev3_right
    board: nice_nano_v2

  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right

  # - shield: kyria_dongle prospector_adapter
  #   board: seeeduino_xiao_ble

  # - shield: bykeeb_leftfga
  #   board: seeeduino_xiao_ble
  # - shield: bykeeb_right
  #   board: seeeduino_xiao_ble

  # - shield: totem_left
  #   board: seeeduino_xiao_ble
  # - shield: totem_right
  #   board: seeeduino_xiao_ble

  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right

  - shield: anywhy_flake_left
    board: nice_nano_v2
    snippet: studio-rpc-usb-uart
  - shield: anywhy_flake_right
    board: nice_nano_v2

  #
  # accessories

  - shield: adept
    board: seeeduino_xiao_ble
    snippet: studio-rpc-usb-uart

  #
  # resets

  - shield: settings_reset
    board: nice_nano_v2

  - shield: settings_reset
    board: seeeduino_xiao_ble

  - shield: settings_reset
    board: seeeduino_xiao_rp2040
