manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: autoferrit
      url-base: https://github.com/autoferrit
  projects:
    - name: zmk
      remote: autoferrit
      revision: sofle
      import: app/west.yml
  self:
    path: config
