manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: spacerock
      url-base: https://github.com/spacerock
    - name: urob
      url-base: https://github.com/urob
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: grassfedreeve
      url-base: https://github.com/grassfedreeve
  projects:
    - name: zmk
      remote: spacerock
      revision: main
      import: app/west.yml
    # Replace the one above with the commented one below when that branch gets merged
    # into ZMK main, or if you're not using pointing devices for your build.
    # Alternatively, you can use your own zmk fork/branch if you are maintaining one.
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    - name: zmk-fingerpunch-keyboards
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    # - name: urob
    #   remote: urob
    #   revision: main
    #   import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    # https://github.com/dhruvinsh/zmk-num-word
    - name: zmk-num-word
      remote: dhruvinsh
      revision: main
    # https://github.com/dhruvinsh/zmk-tri-state
    # - name: zmk-tri-state
    #   remote: dhruvinsh
    #   revision: main
    - name: zmk-keyboards-adept
      remote: grassfedreeve
      revision: main
  self:
    path: config
