manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: spacerockmedia
      url-base: https://github.com/spacerockmedia
    - name: urob
      url-base: https://github.com/urob
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: grassfedreeve
      url-base: https://github.com/grassfedreeve
    - name: anywhy-io
      url-base: https://github.com/anywhy-io
  projects:
    - name: zmk
      remote: spacerockmedia
      revision: main
      import: app/west.yml
    - name: zmk-fingerpunch-keyboards
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    # https://github.com/dhruvinsh/zmk-num-word
    - name: zmk-num-word
      remote: dhruvinsh
      revision: main
    - name: zmk-keyboards-adept
      remote: grassfedreeve
      revision: main
    - name: flake-zmk-module
      remote: anywhy-io
      revision: main
    # https://github.com/dhruvinsh/zmk-tri-state
    # - name: zmk-tri-state
    #   remote: dhruvinsh
    #   revision: main
  self:
    path: config
